version: "3.7"
services:
  ngrok_web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        HOST_USER_ID: ${HOST_USER_ID:-1000}
        HOST_GROUP_ID: ${HOST_GROUP_ID:-1000}
    volumes:
      - ./:/app
    command: /bin/sh -c '/entrypoint.sh'

